import Link from "next/link";
import { ArrowDownIcon, ArrowDownTrayIcon, EnvelopeIcon } from "@heroicons/react/24/outline";
import { ProjectCard, SectionTitle } from "@/components/site";
import { projects } from "@/data/projects";

const skills=["漏斗与增长分析","A/B 测试","统计推断","用户研究","AI 产品分析","Python / SQL / 可视化"];
const roleTags=["AI 数据分析","数据运营","AI 产品","数据产品"];
export default function Home(){return <main id="top"><section className="home-hero"><div className="hero-geometry" aria-hidden="true"><span className="geo-circle"/><span className="geo-square"/><span className="geo-ring"/><span className="geo-dots"/><span className="geo-line"/></div><div className="hero-copy"><span className="eyebrow">DATA · PRODUCT · GROWTH</span><h1><span>Hi~</span>我是宋亭萱</h1><div className="role-tags" aria-label="求职方向">{roleTags.map((role,index)=><span key={role} className={`role-tag role-tag-${index+1}`}>{role}</span>)}</div><p className="hero-line">用数据回答业务问题，<br/>把洞察转化为可执行的增长与产品决策。</p><div className="hero-actions"><a className="hero-action hero-action-primary" href="/song-tingxuan-resume.docx" download><ArrowDownTrayIcon/><span><strong>下载简历</strong><small>查看我的经历与能力</small></span></a><a className="hero-action hero-action-secondary" href="mailto:18504757007@163.com"><EnvelopeIcon/><span><strong>联系我</strong><small>18504757007@163.com</small></span></a></div><Link className="hero-link" href="#projects">继续看看我的项目 <ArrowDownIcon/></Link></div><aside className="hero-profile" aria-label="个人能力概览"><div className="profile-heading"><span>PROFILE / 2026</span><p>面向数据分析、数据运营与 AI 产品方向</p></div><div className="profile-statement">从业务问题出发，<br/>用数据建立判断，<br/>让建议真正落地。</div><div className="profile-proof"><div><span>01</span><p><strong>分析方法</strong><small>漏斗 · 实验 · 用户行为</small></p></div><div><span>02</span><p><strong>业务理解</strong><small>增长 · 运营 · 产品决策</small></p></div><div><span>03</span><p><strong>落地能力</strong><small>SQL · Python · 可视化</small></p></div></div></aside></section>
<section id="projects" className="home-section"><SectionTitle kicker="SELECTED WORK" title="三个项目，三种决策场景" copy="从实验评估、AI 用户偏好到电商漏斗诊断，展示完整的问题定义、分析方法与落地建议。"/><div className="project-grid">{projects.map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div></section>
<section id="skills" className="home-section skills-section"><SectionTitle kicker="CAPABILITIES" title="分析能力" copy="不以工具为终点，以可靠结论和可验证行动为目标。"/><div className="skill-grid">{skills.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,"0")}</span><p>{s}</p></div>)}</div></section></main>}
