import Link from "next/link";
import { AcademicCapIcon, ArrowDownIcon, ArrowDownTrayIcon, BuildingOffice2Icon, EnvelopeIcon } from "@heroicons/react/24/outline";
import { ProjectCard, SectionTitle } from "@/components/site";
import { projects } from "@/data/projects";

const skills=["漏斗与增长分析","A/B 测试","统计推断","用户研究","AI 产品分析","Python / SQL / 可视化"];
const roleTags=["AI 数据分析","数据运营","AI 产品","数据产品"];
const education=[{school:"东北林业大学",degree:"经济统计学 · 本科",period:"2021.09 — 2025.06",meta:"扎实建立经济、统计与数据分析基础",tone:"blue",image:"/schools/nefu-campus.jpg",alt:"东北林业大学正门与主楼"},{school:"澳大利亚国立大学",degree:"统计学 · 硕士",period:"2025.07 — 2027.06",meta:"QS 29 · 深入学习统计建模与推断",tone:"pink",image:"/schools/anu-campus.jpg",alt:"澳大利亚国立大学 Kambri 校园"}];
export default function Home(){return <main id="top"><section className="home-hero"><div className="hero-geometry" aria-hidden="true"><span className="geo-circle"/><span className="geo-square"/><span className="geo-ring"/><span className="geo-dots"/><span className="geo-line"/></div><div className="hero-copy"><span className="eyebrow">DATA · PRODUCT · GROWTH</span><h1><span>Hi~</span>我是宋亭萱</h1><div className="role-tags" aria-label="求职方向">{roleTags.map((role,index)=><span key={role} className={`role-tag role-tag-${index+1}`}>{role}</span>)}</div><p className="hero-line">用数据回答业务问题，<br/>把洞察转化为可执行的增长与产品决策。</p><div className="hero-actions"><a className="hero-action hero-action-primary" href="/song-tingxuan-resume.docx" download><ArrowDownTrayIcon/><span><strong>下载简历</strong><small>查看我的经历与能力</small></span></a><a className="hero-action hero-action-secondary" href="mailto:18504757007@163.com"><EnvelopeIcon/><span><strong>联系我</strong><small>18504757007@163.com</small></span></a></div><Link className="hero-link" href="#projects">继续看看我的项目 <ArrowDownIcon/></Link></div><aside className="hero-profile" aria-label="个人能力概览"><div className="profile-heading"><span>PROFILE / 2026</span><p>面向数据分析、数据运营与 AI 产品方向</p></div><div className="profile-statement">从业务问题出发，<br/>用数据建立判断，<br/>让建议真正落地。</div><div className="profile-proof"><div><span>01</span><p><strong>分析方法</strong><small>漏斗 · 实验 · 用户行为</small></p></div><div><span>02</span><p><strong>业务理解</strong><small>增长 · 运营 · 产品决策</small></p></div><div><span>03</span><p><strong>落地能力</strong><small>SQL · Python · 可视化</small></p></div></div></aside></section>
<section id="about" className="home-section about-section reveal-section"><SectionTitle kicker="ABOUT ME" title="关于我" copy="让面试官在 30 秒内理解你的经历、动机和求职匹配度。"/><div className="about-grid"><div className="portrait-placeholder" role="img" aria-label="个人职业照占位"><span>PHOTO</span><p>这里建议放一张<br/>自然、清晰的个人职业照</p><small>推荐半身照 · 明亮背景 · 4:5</small></div><div className="about-copy"><span>MY STORY</span><h3>从经济统计到 AI 产品，<br/>我关注数据如何真正改变决策。</h3><p>我具备经济统计与统计学训练，拥有数据运营实践和三个完整分析项目，能够从业务问题出发完成指标设计、分析验证与策略输出。</p><div className="info-placeholders"><div><strong>求职城市</strong><span>这里建议填写目标城市</span></div><div><strong>到岗时间</strong><span>这里建议填写最早到岗日期</span></div><div><strong>个人优势</strong><span>这里建议补充一句差异化优势</span></div></div></div></div></section>
<section id="education" className="home-section education-section reveal-section"><SectionTitle kicker="EDUCATION" title="学历背景" copy="跨越经济统计与统计学训练，持续建立从业务理解到量化判断的能力。"/><div className="education-grid">{education.map((item,index)=><article key={item.school} className={`education-card education-${item.tone}`} tabIndex={0}><div className="education-card-top"><span>0{index+1}</span><AcademicCapIcon/></div><div className="education-photo"><img src={item.image} alt={item.alt} loading="lazy"/><span>校园影像</span></div><div><p className="education-period">{item.period}</p><h3>{item.school}</h3><p className="education-degree">{item.degree}</p></div><p className="education-note">{item.meta}<span aria-hidden>↗</span></p></article>)}</div></section>
<section id="experience" className="home-section experience-section reveal-section"><SectionTitle kicker="EXPERIENCE" title="实习经历" copy="在真实业务流程中完成指标监控、漏斗梳理、数据治理与运营策略输出。"/><article className="experience-card"><div className="experience-summary"><div className="experience-heading"><BuildingOffice2Icon/><div><span>2024.08 — 2024.10</span><h3>高顿教育</h3><p>数据运营实习生</p></div></div><div className="experience-photo"><img src="/visuals/data-operations-internship.webp" alt="数据运营与业务分析工作场景" loading="lazy"/><span>DATA OPERATIONS</span></div></div><div className="experience-details"><div><span>01</span><p><strong>指标监控</strong>持续跟踪课程报名、咨询、直播到课及成交等 5+ 项核心指标，支持 10+ 场财经课程直播监控及复盘。</p></div><div><span>02</span><p><strong>业务分析</strong>梳理 3 类财经课程业务流程，构建曝光至成交的 6 个核心转化节点，识别关键流失环节。</p></div><div><span>03</span><p><strong>数据治理</strong>使用 SQL 与 Excel 完成多来源数据清洗、字段统一及口径标准化，建立固定分析模板。</p></div><div><span>04</span><p><strong>策略输出</strong>提出多触点提醒、高意向用户优先跟进、未到课用户二次邀约及课程回放触达方案。</p></div></div></article></section>
<section id="projects" className="home-section reveal-section"><SectionTitle kicker="SELECTED WORK" title="三个项目，三种决策场景" copy="从实验评估、AI 用户偏好到电商漏斗诊断，展示完整的问题定义、分析方法与落地建议。"/><div className="project-grid">{projects.map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div></section>
<section id="skills" className="home-section skills-section reveal-section"><SectionTitle kicker="CAPABILITIES" title="分析能力" copy="不以工具为终点，以可靠结论和可验证行动为目标。"/><div className="skill-grid">{skills.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,"0")}</span><p>{s}</p></div>)}</div></section></main>}
