import Link from "next/link";
import { AcademicCapIcon, ArrowDownIcon, ArrowDownTrayIcon, BuildingOffice2Icon, EnvelopeIcon } from "@heroicons/react/24/outline";
import { ProjectCard, SectionTitle } from "@/components/site";
import { projects } from "@/data/projects";

const skills=[
 {title:"漏斗与增长分析",copy:"搭建转化链路，定位流失节点，量化增长机会，输出分层运营策略"},
 {title:"A/B 测试",copy:"实验设计、样本量预估、显著性检验、稳健性校验、实验收益评估"},
 {title:"统计推断",copy:"假设检验、分层分析、抽样偏差校正、因果识别基础"},
 {title:"用户研究",copy:"用户行为分层、需求挖掘、人群特征拆解、用户路径分析"},
 {title:"AI 产品分析",copy:"大模型使用行为分析、模型效果对比、产品交互策略评估"},
 {title:"Python / SQL / 可视化",copy:"数据提取清洗、特征加工、统计建模、可视化报告输出"},
];
const roleTags=["AI 数据分析","数据运营","AI 产品","数据分析"];
const education=[{school:"东北林业大学",degree:"经济统计学・本科",period:"2021.09–2025.06",meta:"搭建经济学、统计学与数据分析基础，掌握描述统计、回归分析、抽样理论。",tone:"blue",image:"/schools/nefu-campus.jpg",alt:"东北林业大学正门与主楼",badge:""},{school:"澳大利亚国立大学",degree:"统计学・硕士",period:"2025.07–2027.06",meta:"深耕统计建模、假设检验、因果推断，为实验分析、用户行为建模提供理论支撑。",tone:"pink",image:"/schools/anu-campus.jpg",alt:"澳大利亚国立大学 Kambri 校园",badge:"QS 29"}];
export default function Home(){return <main id="top"><section className="home-hero"><div className="hero-geometry" aria-hidden="true"><span className="geo-circle"/><span className="geo-square"/><span className="geo-ring"/><span className="geo-dots"/><span className="geo-line"/></div><div className="hero-copy"><span className="eyebrow">DATA · PRODUCT · GROWTH</span><h1><span>Hi~</span>我是宋亭萱</h1><div className="role-tags" aria-label="求职方向">{roleTags.map((role,index)=><span key={role} className={`role-tag role-tag-${index+1}`}>{role}</span>)}</div><p className="hero-line">用数据回答业务问题，<br/>把洞察转化为可执行的增长与产品决策。</p><div className="hero-actions"><a className="hero-action hero-action-primary" href="/song-tingxuan-resume.pdf" download><ArrowDownTrayIcon/><span><strong>下载简历</strong><small>查看我的经历与能力</small></span></a><a className="hero-action hero-action-secondary" href="mailto:18504757007@163.com"><EnvelopeIcon/><span><strong>联系我</strong><small>18504757007@163.com</small></span></a></div><Link className="hero-link" href="#projects">继续看看我的项目 <ArrowDownIcon/></Link></div><aside className="hero-profile" aria-label="个人能力概览"><div className="profile-heading"><span>PROFILE / 2026</span><p>面向数据分析、数据运营与 AI 产品方向</p></div><div className="profile-statement">从业务问题出发，<br/>用数据建立判断，<br/>让建议真正落地。</div><div className="profile-proof"><div><span>01</span><p><strong>分析方法</strong><small>漏斗 · 实验 · 用户行为</small></p></div><div><span>02</span><p><strong>业务理解</strong><small>增长 · 运营 · 产品决策</small></p></div><div><span>03</span><p><strong>落地能力</strong><small>SQL · Python · 可视化</small></p></div></div></aside></section>
<section id="about" className="home-section about-section reveal-section"><SectionTitle kicker="ABOUT ME" title="关于我" copy="经济统计本科与统计学硕士训练，让我既能理解业务，也能用严谨方法验证判断并推动行动。"/><div className="about-grid"><figure className="portrait-photo"><img src="/visuals/song-tingxuan-portrait-literary.webp" alt="宋亭萱职业照" loading="lazy"/></figure><div className="about-copy"><span>MY STORY</span><h3>从业务问题到可靠结论，<br/>我希望让数据真正参与决策。</h3><p>拥有经济统计本科与统计学硕士专业训练，具备一段数据运营实习经验，落地 <strong className="number-highlight">3 个</strong>完整数据分析项目。熟练完成指标体系设计、数据清洗、统计验证、洞察提炼到策略输出完整链路；同时持续拓展工程能力，尝试通过 Vibe Coding 将分析思路做成可交互、可验证的线上作品。</p><div className="info-placeholders"><div><strong>职业期待</strong><span>参与具备真实业务价值的数据与产品决策，持续深耕增长分析方向。</span></div><div><strong>成长方向</strong><span>补齐工程开发能力，让数据分析结论更快落地。</span></div><div><strong>差异化优势</strong><span>兼具统计学严谨性、业务敏感度，擅长把量化结论转化为可执行方案。</span></div></div></div></div></section>
<section id="education" className="home-section education-section reveal-section"><SectionTitle kicker="EDUCATION" title="学历背景" copy="跨经济统计与统计学训练，持续建立从业务理解到量化判断的能力。"/><div className="education-grid">{education.map((item,index)=><article key={item.school} className={`education-card education-${item.tone}`} tabIndex={0}><div className="education-card-top"><span>0{index+1}</span><AcademicCapIcon/></div><div className="education-photo"><img src={item.image} alt={item.alt} loading="lazy"/><span>校园影像</span></div><div><p className="education-period">{item.period}</p><h3>{item.school}{item.badge&&<small className="school-badge">{item.badge}</small>}</h3><p className="education-degree">{item.degree}</p></div><p className="education-note">{item.meta}<span aria-hidden>↗</span></p></article>)}</div></section>
<section id="experience" className="home-section experience-section reveal-section"><SectionTitle kicker="EXPERIENCE" title="实习经历" copy="在跨境电商与教育业务场景中，完成商品数据治理、指标监控、业务分析与运营策略输出。"/><div className="experience-list"><article className="experience-card experience-card-current"><div className="experience-summary"><div className="experience-heading"><BuildingOffice2Icon/><div><span>2025.11 — 至今</span><h3>eBay 跨境电商</h3><p>商品数据运营</p><small className="experience-status">CURRENT · 在职</small></div></div><div className="experience-photo experience-photo-commerce"><img src="/visuals/data-operations-internship.webp" alt="跨境电商商品数据治理与运营工作场景" loading="lazy"/><span>ECOMMERCE · DATA OPERATIONS</span></div></div><div className="experience-details"><div><span>01</span><p><strong>数据治理</strong>参与店铺 0–1 冷启动，开展商品元数据治理，标准化梳理标题、类目及多语种描述，统一商品信息规范。</p></div><div><span>02</span><p><strong>AI 提效</strong>依托 LLM 大模型落地业务提效场景，结合品类特征、人群偏好与平台规则，批量生成合规商品候选文案；建立 AI 输出校验机制，筛选过滤同质化、误差性内容，有效降低人工上品成本，保障上线数据质量。</p></div><div><span>03</span><p><strong>指标监控</strong>以 SKU 为分析单元，解析流量、销售报表，监控曝光、动销等指标，定位低效商品并输出结构优化建议。</p></div><div><span>04</span><p><strong>数据复盘</strong>跟踪 GMV、广告 ROI 指标，拆解单品与广告投放效率，输出调优方案，支撑精细化运营与策略迭代。</p></div></div></article><article className="experience-card"><div className="experience-summary"><div className="experience-heading"><BuildingOffice2Icon/><div><span>2024.08 — 2024.10</span><h3>高顿教育</h3><p>数据运营实习生</p></div></div><div className="experience-photo"><img src="/visuals/data-operations-internship.webp" alt="数据运营与业务分析工作场景" loading="lazy"/><span>DATA OPERATIONS</span></div></div><div className="experience-details"><div><span>01</span><p><strong>指标监控</strong>持续跟踪课程报名、咨询、直播到课及成交等 5+ 项核心指标，支持 10+ 场财经课程直播监控及复盘。</p></div><div><span>02</span><p><strong>业务分析</strong>梳理 3 类财经课程业务流程，构建曝光至成交的 6 个核心转化节点，识别关键流失环节。</p></div><div><span>03</span><p><strong>数据治理</strong>使用 SQL 与 Excel 完成多来源数据清洗、字段统一及口径标准化，建立固定分析模板。</p></div><div><span>04</span><p><strong>策略输出</strong>提出多触点提醒、高意向用户优先跟进、未到课用户二次邀约及课程回放触达方案。</p></div></div></article></div></section>
<section id="projects" className="home-section reveal-section"><SectionTitle kicker="SELECTED WORK" title="三个项目，三种决策场景" copy="从实验评估、AI 用户偏好到电商漏斗诊断，展示完整的问题定义、分析方法与落地建议。"/><div className="project-grid">{projects.map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div></section>
<section id="skills" className="home-section skills-section reveal-section"><SectionTitle kicker="CAPABILITIES" title="分析能力" copy="不以工具为终点，以可靠结论和可验证行动为目标。"/><div className="skill-grid">{skills.map((skill,i)=><div key={skill.title}><span>{String(i+1).padStart(2,"0")}</span><p>{skill.title}</p><small>{skill.copy}</small></div>)}</div></section></main>}
