import Link from "next/link";
import { AcademicCapIcon, ArrowUpRightIcon, BriefcaseIcon, ChartBarIcon, DocumentTextIcon, EnvelopeIcon, Squares2X2Icon, UserIcon } from "@heroicons/react/24/outline";
import { projectCardDetails, projects } from "@/data/projects";

export function Header(){return <header className="site-header"><Link href="/" className="brand"><span className="brand-mark">宋</span><span>宋亭萱</span></Link><nav aria-label="主导航"><Link href="/#education">学历背景</Link><Link href="/#experience">实习经历</Link><Link href="/#projects">项目经历</Link><a href="https://github.com/lulu04201226" target="_blank" rel="noreferrer">GitHub <span aria-hidden>↗</span></a></nav></header>}
export function Footer(){return <footer><div><p className="footer-title">从数据中找到值得行动的答案。</p><p className="muted">数据分析 · 产品分析</p></div><div className="footer-links">{projects.map(p=><a key={p.slug} href={p.github} target="_blank" rel="noreferrer" aria-label={`${p.title} GitHub 仓库（新窗口打开）`}>{p.title}<ArrowUpRightIcon/></a>)}</div></footer>}
export function ProjectCard({project,index}:{project:(typeof projects)[number],index:number}){const detail=projectCardDetails[project.slug];return <article className="project-card project-card-detailed"><div className="card-top"><span className="index">0{index+1}</span><span className="tag">{project.eyebrow}</span></div><h3>{project.title}</h3><p className="question">{project.question}</p><div className="project-role">{detail.role}</div><dl className="project-brief"><div><dt>业务目标</dt><dd>{detail.goal}</dd></div><div><dt>分析方法</dt><dd><span className="method-chips">{detail.methods.map(method=><span key={method}>{method}</span>)}</span></dd></div><div><dt>量化结论</dt><dd><strong>{detail.conclusion}</strong><span className="conclusion-reading">{detail.interpretation}</span></dd></div><div><dt>最终交付</dt><dd>{detail.deliverable}</dd></div></dl><Link className="text-link" href={`/projects/${project.slug}`}>查看完整案例 <span aria-hidden>→</span></Link></article>}
export function SectionTitle({kicker,title,copy}:{kicker:string,title:string,copy?:string}){return <div className="section-title"><span>{kicker}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function GithubButton({href,label="查看项目代码"}:{href:string,label?:string}){return <a className="button" href={href} target="_blank" rel="noreferrer" aria-label={`${label}（新窗口打开）`}><ChartBarIcon/>{label}<ArrowUpRightIcon/></a>}
export function FeishuButton({href}:{href:string}){const preview=href.startsWith("#");return <a className={`button button-feishu${preview?" is-preview-disabled":""}`} href={href} target={preview?undefined:"_blank"} rel={preview?undefined:"noreferrer"} aria-disabled={preview||undefined} aria-label={preview?"飞书文档将在正式发布后开放":"查看飞书文档（新窗口打开）"}><DocumentTextIcon/>{preview?"飞书文档待开放":"查看飞书文档"}<ArrowUpRightIcon/></a>}
export function BackToTop(){return <a className="back-top" href="#top" aria-label="返回页面顶部">↑</a>}
export function FloatingDock(){return <nav className="floating-dock" aria-label="快捷导航"><a href="#about"><UserIcon/><span>关于我</span></a><a href="#education"><AcademicCapIcon/><span>学历</span></a><a href="#experience"><BriefcaseIcon/><span>实习</span></a><a href="#projects"><Squares2X2Icon/><span>项目</span></a><a href="mailto:18504757007@163.com"><EnvelopeIcon/><span>联系</span></a></nav>}
